### ISSUE TITLE
versionamento das bibliotecas.

### ISSUE THREAD

**Issue by EvertonMelo** [ComunidadeExpresso/expressomobile#1]
Ola
não seria interessante vocês versionarem as bibliotecas? 
pois existem várias versão de Androids vejo que sem o versionamento, os requisitos mínimos ficam muito ambíguos.

**Comment by pereirajair** [comment]
Olá Everton, Sobre quais bibliotecas você está se referindo? 

Nesta nova versão todas as bibliotecas estão sendo versionadas com o BOWER. acredito que seja só rodar o "bower install" que ele irá baixar todas as dependências do projeto.

Esta ainda é uma versão em desenvolvimento, portanto ainda não está pronta para produção.

**Comment by EvertonMelo** [comment]
@pereirajair 
favor informar as versoes dessa libs:

Biliotecas utilizadas

- Cordova	
- Bacbkone
- RequireJS
- Underscore
- Polymer
- Webcomponents
- jQuery
- Moment.js
- jQuery XMPP
